### PR TITLE
Create it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by dar5hak** [comment]
Huh, strange. Why is this conflicting with the extra po?

**Comment by dar5hak** [comment]
I cannot merge #9 before this, or else the Flatpak build will fail.

**Comment by albanobattistella** [comment]
> I cannot merge #9 before this, or else the Flatpak build will fail.

Hi,
there was a space, I fixed but I don't know if works.
No other error I found.

**Comment by dar5hak** [comment]
Yeah yeah, no problems with your translation. It's just that I don't get why there are conflicts, considering this was in a separate file from the other pull requests.

Don't worry, I'll resolve it.

**Comment by dar5hak** [comment]
Okay, I found the issue. In #12, we merged the file `po/it.po`, when in fact, we should have merged `po/extra/it.po`, keeping `po/it.po` for this PR. I moved it, and we can now merge this.

**Pull request merged**
