### PR TITLE
Improve meson project structure

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi @dar5hak I made some cleanup to your project structure, especially with meson files. Better to merge these changes before adding French translation. I created a new folder named `extra` into the `po` folder to split translations between the main ones and the metadata ones.

### CODE REVIEW

**Comment by dar5hak** [comment]
This is all right, except for one change: I need to update the pot for appdata.xml, because there's one change that exists in the Spanish translation but is lost in English and the pot file. (That was my mistake.)

What's the command to generate the pot for the extra files?

**Comment by NathanBnm** [comment]
> What's the command to generate the pot for the extra files?

You can use the following command `ninja extra-update-po`

**Comment by dar5hak** [comment]
Done. Merci beaucoup, @NathanBnm!

I didn't give much thought to the project config and mostly just copied and pasted from Badger. Now it makes a lot of sense and is far cleaner. Your experience working on several projects helped! :smiley:

**Review by dar5hak — COMMENTED** [review]
All good.

**Pull request merged**
